name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

env:
  AKS_CLUSTER_NAME: wiz-aks-cluster
  RESOURCE_GROUP: wiz-exercise-rg
  CONTAINER_APP_NAME: wiz-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get ACR Name and Credentials
      id: get-acr
      run: |
        # Get ACR name
        ACR_NAME=$(az acr list --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].name" -o tsv)
        echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
        echo "Found ACR: $ACR_NAME"
        
        # Get ACR credentials
        ACR_CREDS=$(az acr credential show --name $ACR_NAME)
        ACR_USERNAME=$(echo $ACR_CREDS | jq -r '.username')
        ACR_PASSWORD=$(echo $ACR_CREDS | jq -r '.passwords[0].value')
        
        # Set credentials as environment variables
        echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Build and push container image
      run: |
        # Build the image with both latest and commit SHA tags
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
                    -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest .
        
        # Push both tags
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

    - name: Create Kubernetes namespace if not exists
      run: |
        kubectl create namespace wiz-app --dry-run=client -o yaml | kubectl apply -f -

    - name: Create MongoDB connection string secret
      run: |
        kubectl create secret generic mongodb-connection \
          --namespace wiz-app \
          --from-literal=connection-string="${{ secrets.MONGODB_CONNECTION_STRING }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        # Update the deployment with the new image
        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${{ env.CONTAINER_APP_NAME }}
          namespace: wiz-app
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: ${{ env.CONTAINER_APP_NAME }}
          template:
            metadata:
              labels:
                app: ${{ env.CONTAINER_APP_NAME }}
            spec:
              containers:
              - name: ${{ env.CONTAINER_APP_NAME }}
                image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
                ports:
                - containerPort: 3000
                env:
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-connection
                      key: connection-string
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
                readinessProbe:
                  httpGet:
                    path: /health
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: ${{ env.CONTAINER_APP_NAME }}
          namespace: wiz-app
        spec:
          type: LoadBalancer
          ports:
          - port: 80
            targetPort: 3000
          selector:
            app: ${{ env.CONTAINER_APP_NAME }}
        EOF

    - name: Wait for deployment to complete
      run: |
        kubectl rollout status deployment/${{ env.CONTAINER_APP_NAME }} -n wiz-app

    - name: Get service URL
      run: |
        echo "Waiting for LoadBalancer IP..."
        sleep 30
        SERVICE_IP=$(kubectl get service ${{ env.CONTAINER_APP_NAME }} -n wiz-app -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Application is available at: http://$SERVICE_IP" 