name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-azure-access:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List Resource Groups
      run: |
        echo "Listing Resource Groups..."
        az group list --query "[].{name:name, location:location}" -o table

    - name: List AKS Clusters
      run: |
        echo "Listing AKS Clusters..."
        az aks list --query "[].{name:name, resourceGroup:resourceGroup, status:powerState.code}" -o table

    - name: List ACR Repositories
      run: |
        echo "Listing ACR Repositories..."
        az acr repository list --name wizacr -o table

    - name: Test AKS Access
      run: |
        echo "Testing AKS Access..."
        az aks get-credentials --resource-group wiz-exercise-rg --name wiz-aks-cluster
        kubectl get nodes 