name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-azure-access:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

    - name: List Resource Groups
      run: |
        echo "Listing Resource Groups..."
        az group list --query "[].{name:name, location:location}" -o table

    - name: List AKS Clusters
      run: |
        echo "Listing AKS Clusters..."
        az aks list --query "[].{name:name, resourceGroup:resourceGroup, status:powerState.code}" -o table

    - name: Get ACR Name and Credentials
      id: get-acr
      run: |
        # Get ACR name
        ACR_NAME=$(az acr list --resource-group wiz-exercise-rg --query "[0].name" -o tsv)
        echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
        echo "Found ACR: $ACR_NAME"
        
        # Get ACR credentials
        ACR_CREDS=$(az acr credential show --name $ACR_NAME)
        ACR_USERNAME=$(echo $ACR_CREDS | jq -r '.username')
        ACR_PASSWORD=$(echo $ACR_CREDS | jq -r '.passwords[0].value')
        
        # Set credentials as environment variables
        echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: List ACR Repositories
      run: |
        echo "Listing ACR Repositories..."
        az acr repository list --name ${{ env.ACR_NAME }} -o table

    - name: Test AKS Access
      run: |
        echo "Testing AKS Access..."
        az aks get-credentials --resource-group wiz-exercise-rg --name wiz-aks-cluster
        kubectl get nodes 